security:
    # On désactive temporairement le chiffrement complexe pour le test en mémoire
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'

    providers:
        users_in_memory:
            memory:
                users:
                    # Le mot de passe ici est écrit en clair pour éviter tout bug YAML
                    farouck@admin.com: { password: 'admin123', roles: ['ROLE_USER'] }

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/wish, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
